//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietProfile
    {
        public string UserName { get; set; }
        public MealPlanner.DTO.Enums.DietChoice DietChoice { get; set; }
        public bool Gluten { get; set; }
        public bool Peanut { get; set; }
        public bool Eggs { get; set; }
        public bool Dairy { get; set; }
        public bool Soy { get; set; }
        public bool Onion { get; set; }
        public bool Nuts { get; set; }
        public bool Seafood { get; set; }
    
        public virtual User User { get; set; }
    }
}
