//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MealPlannerDbEntities : DbContext
    {
        public MealPlannerDbEntities()
            : base("name=MealPlannerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhysicalProfile> PhysicalProfiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<DietProfile> DietProfiles { get; set; }
    }
}
