//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalProfile
    {
        public MealPlanner.DTO.Enums.DoOption DoOption { get; set; }
        public MealPlanner.DTO.Enums.Gender Gender { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public int Age { get; set; }
        public MealPlanner.DTO.Enums.ActivityLevel ActivityLevel { get; set; }
        public Nullable<double> FinalWeight { get; set; }
        public Nullable<int> DaysToGo { get; set; }
        public string UserName { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<int> SuggestedCalories { get; set; }
    
        public virtual User User { get; set; }
    }
}
